server:
  session-timeout: 1800
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 80
  context-path: /
#    uri-encoding: utf-8
security:
  basic:
    enabled: false
spring:
  thymeleaf:
    mode: HTML
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools: 
    restart:
      enabled: true    
#默认redis,可选ehcache
  cache: 
    type: redis 
    ehcache:
      config: classpath:config/ehcache.xml
      
####################### 配置分页(helperDialect=mysql/oracle，作为数据库标记)###########################
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    pageSizeZero: true
    params: count=countSql
    
#mybatis配置
mybatis: 
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.fc.**.domain, com.ereal.**.domain
 
#[弃用]调整至 spring cache type【shiro.用户，权限，session，spring.cache通用】
#cacheType: ehcache

##########################小程序相关配置#############################
wxapp:
  appId: wxcd7895bfb18c1de5
  secret: 6b60bae7d2c09aad8ecc1678490d81b6
  grantType: authorization_code
  sessionHost: https://api.weixin.qq.com/sns/jscode2session